export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAILURE = 'ADMIN_REGISTER_FAILURE';

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';


export const ADD_BUS_REQUEST = "ADD_BUS_REQUEST";
export const ADD_BUS_SUCCESS = "ADD_BUS_SUCCESS";
export const ADD_BUS_FAIL = "ADD_BUS_FAIL";

export const FETCH_BUSES_REQUEST = "FETCH_BUSES_REQUEST";
export const FETCH_BUSES_SUCCESS = "FETCH_BUSES_SUCCESS";
export const FETCH_BUSES_FAIL = "FETCH_BUSES_FAIL";

