export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAILURE = 'ADMIN_REGISTER_FAILURE';

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';


export const ADD_BUS_REQUEST = "ADD_BUS_REQUEST";
export const ADD_BUS_SUCCESS = "ADD_BUS_SUCCESS";
export const ADD_BUS_FAIL = "ADD_BUS_FAIL";

export const FETCH_BUSES_REQUEST = "FETCH_BUSES_REQUEST";
export const FETCH_BUSES_SUCCESS = "FETCH_BUSES_SUCCESS";
export const FETCH_BUSES_FAIL = "FETCH_BUSES_FAIL";

export const UPDATE_BUS_REQUEST = "UPDATE_BUS_REQUEST";
export const UPDATE_BUS_SUCCESS = "UPDATE_BUS_SUCCESS";
export const UPDATE_BUS_FAIL = "UPDATE_BUS_FAIL";

export const DELETE_BUS_REQUEST = "DELETE_BUS_REQUEST";
export const DELETE_BUS_SUCCESS = "DELETE_BUS_SUCCESS";
export const DELETE_BUS_FAIL = "DELETE_BUS_FAIL";


export const FETCH_PROMOS_REQUEST = "FETCH_PROMOS_REQUEST";
export const FETCH_PROMOS_SUCCESS = "FETCH_PROMOS_SUCCESS";
export const FETCH_PROMOS_FAIL = "FETCH_PROMOS_FAIL";

export const ADD_PROMO_REQUEST = "ADD_PROMO_REQUEST";
export const ADD_PROMO_SUCCESS = "ADD_PROMO_SUCCESS";
export const ADD_PROMO_FAIL = "ADD_PROMO_FAIL";

export const UPDATE_PROMO_REQUEST = "UPDATE_PROMO_REQUEST";
export const UPDATE_PROMO_SUCCESS = "UPDATE_PROMO_SUCCESS";
export const UPDATE_PROMO_FAIL = "UPDATE_PROMO_FAIL";

export const DELETE_PROMO_REQUEST = "DELETE_PROMO_REQUEST";
export const DELETE_PROMO_SUCCESS = "DELETE_PROMO_SUCCESS";
export const DELETE_PROMO_FAIL = "DELETE_PROMO_FAIL";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_USER_BOOKINGS_REQUEST = "FETCH_USER_BOOKINGS_REQUEST";
export const FETCH_USER_BOOKINGS_SUCCESS = "FETCH_USER_BOOKINGS_SUCCESS";
export const FETCH_USER_BOOKINGS_FAIL = "FETCH_USER_BOOKINGS_FAIL";

export const FETCH_REVENUE_REQUEST = 'FETCH_REVENUE_REQUEST';
export const FETCH_REVENUE_SUCCESS = 'FETCH_REVENUE_SUCCESS';
export const FETCH_REVENUE_FAIL = 'FETCH_REVENUE_FAIL';

export const CANCEL_BUS_BOOKINGS_REQUEST = 'CANCEL_BUS_BOOKINGS_REQUEST';
export const CANCEL_BUS_BOOKINGS_SUCCESS = 'CANCEL_BUS_BOOKINGS_SUCCESS';
export const CANCEL_BUS_BOOKINGS_FAIL = 'CANCEL_BUS_BOOKINGS_FAIL';