export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";


export const FETCH_USERSBUS_REQUEST = "FETCH_USERSBUS_REQUEST";
export const FETCH_USERSBUS_SUCCESS = "FETCH_USERSBUS_SUCCESS";
export const FETCH_USERSBUS_FAIL = "FETCH_USERSBUS_SUCCESS";


export const FETCH_USERSPROMO_REQUEST = "FETCH_USERSPROMO_REQUEST";
export const FETCH_USERSPROMO_SUCCESS = "FETCH_USERSPROMO_SUCCESS";
export const FETCH_USERSPROMO_FAIL = "FETCH_USERSPROMO_FAIL";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";


export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";
export const BOOK_TICKET_FAIL = "BOOK_TICKET_FAIL";

export const FETCH_TICKET_REQUEST  = "FETCH_TICKET_REQUEST";
export const FETCH_TICKET_SUCCESS  = "FETCH_TICKET_SUCCESS";
export const FETCH_TICKET_FAIL  = "FETCH_TICKET_FAIL";





